services:
  api:
    container_name: api
    build: .
    ports:
      - 8001:8001
    volumes:
      - ./storage:/app
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]